.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. soferox_qt test_soferox_qt
clean: FORCE
	$(MAKE) -C .. soferox_qt_clean test_soferox_qt_clean
check: FORCE
	$(MAKE) -C .. test_soferox_qt_check
soferox-qt soferox-qt.exe: FORCE
	 $(MAKE) -C .. soferox_qt
